# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_key', models.CharField(max_length=50, unique=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, unique=True)),
                ('project_desc', models.TextField(blank='Ture', max_length=400, null='Ture')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u5206\u7ec4',
                'verbose_name_plural': '\u9879\u76ee\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Projects_to_Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salt.Hosts')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salt.Projects')),
            ],
        ),
    ]
