# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosts',
            options={'verbose_name': '\u4e3b\u673a\u5217\u8868', 'verbose_name_plural': '\u4e3b\u673a\u5217\u8868'},
        ),
        migrations.AlterModelOptions(
            name='projects_to_host',
            options={'verbose_name': '\u9879\u76ee\u4e3b\u673a\u5bf9\u5e94\u5173\u7cfb\u8868', 'verbose_name_plural': '\u9879\u76ee\u4e3b\u673a\u5bf9\u5e94\u5173\u7cfb\u8868'},
        ),
        migrations.AddField(
            model_name='projects',
            name='filter_re',
            field=models.CharField(blank='Ture', max_length=100, null='Ture'),
        ),
        migrations.AddField(
            model_name='projects',
            name='update_cmd',
            field=models.CharField(blank='Ture', max_length=1000, null='Ture'),
        ),
    ]
